annotations:
  max_scale_version: 24.04.1
  min_scale_version: 24.04.0
  truecharts.org/SCALE-support: "true"
  truecharts.org/category: utilities
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.11"
apiVersion: v2
appVersion: "19.1.0"
dependencies:
  - name: common
    version: 23.0.0
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
description: Zabbix is an enterprise-class open source distributed monitoring solution.
home: https://truecharts.org/charts/incubator/zabbix
icon: https://truecharts.org/img/hotlink-ok/chart-icons/zabbix.png
keywords:
  - zabbix
  - monitoring
kubeVersion: ">=1.24.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: zabbix
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/zabbix
type: application
version: "7.0.0"

