image:
  repository: zabbix/zabbix-server-pgsql
  tag: 7.0@sha256:adcef2675dc09bb7ccd550c7f9245118ff96c067626bcd6fec6f36f5d33eac43
  pullPolicy: IfNotPresent

frontendImage:
  repository: zabbix/zabbix-web-nginx-pgsql
  tag: 7.0@sha256:10d5dfa05ddbab895d9cfbdf55bf51d80243af61bfb3586d467989747ccbc875
  pullPolicy: IfNotPresent

agent2Image:
  repository: zabbix/zabbix-agent2
  tag: 7.0@sha256:7ae9e169dfc3235f00329afadd3eb252f7bc5a87ce2de9dc016fd67ec220b13f
  pullPolicy: IfNotPresent

snmptrapsImage:
  repository: zabbix/zabbix-snmptraps
  tag: 7.0@sha256:de79024b4dea93e996e5ce17e367693948d43df798b5b2733065abb8719bfc03
  pullPolicy: IfNotPresent

javaGatewayImage:
  repository: zabbix/zabbix-java-gateway
  tag: 7.0@sha256:d166e1983cca476b21a9a97a5a13860eef0e59e44772b68b4a34638189d8c630
  pullPolicy: IfNotPresent

webServiceImage:
  repository: zabbix/zabbix-web-service
  tag: 7.0@sha256:ae8e77582717ac401f16b052e05520cfdcde55383069469f45e37363c8c3b4e3
  pullPolicy: IfNotPresent

tty: true

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 1997
  runAsGroup: 0
  
database:
  # -- Database type,
  # must be one of: 'sqlite', 'mysql' or 'postgresql'.
  type: postgresql
  # -- Enable DB Write-Ahead-Log for SQLite,
  wal: true

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DB_SERVER_HOST:
              secretKeyRef:
                name: cnpg-main-urls
                key: host
            POSTGRES_USER:  "{{ .Values.cnpg.main.user }}"
            POSTGRES_DB: "{{ .Values.cnpg.main.database }}"
            POSTGRES_PASSWORD:
              secretKeyRef:
                name: cnpg-main-user
                key: password
            
zabbix:
  # -- https://www.zabbix.com/documentation/current/en/manual/appendix/config/zabbix_server
  server:
    listen_backlog: 0
    debug_level: 3
    load_modules: []
    timeout: 4
    service_manager_sync_freq: 60
    start_report_writers: 0
    start_pollers: 5
    start_ipmi_pollers: 0
    start_preprocessors: 3
    start_pollers_unreachable: 1
    start_trappers: 5
    start_pingers: 1
    start_discoverers: 1
    start_history_pollers: 5
    start_http_pollers: 1
    start_obdc_pollers: 1
    start_timers: 1
    start_escalators: 1
    start_alerters: 3
    start_java_pollers: 5
    start_proxy_pollers: 1
    start_db_syncers: 4
    start_lld_processors: 2
    start_vmware_collectors: 0
    vmware_frequency: 60
    vmware_perf_frequency: 60
    vmware_cache_size: 8M
    vmware_timeout: 10
    housekeeping_freq: 1
    max_housekeeper_delete: 5000
    problem_housekeeper_freq: 60
    cache_size: 32M
    cache_update_freq: 60
    history_cache_size: 16M
    history_index_cache_size: 4M
    history_storage_date_index: false
    trend_cache_size: 4M
    trend_function_cache_size: 4M
    value_cache_size: 8M
    trapper_timeout: 300
    unreachable_period: 45
    unreachable_delay: 15
    unavailable_delay: 60
    log_slow_queries: 3000
    proxy_config_freq: 3600
    proxy_data_freq: 1
    export_file_size: 1G
    export_type: []
    stats_allowed_ips: []
  frontend:
    server_name: My Zabbix Server
    enable_access_logs: true
    max_execution_time: 300
    memory_limit: 128M
    post_max_size: 16M
    upload_max_file_size: 2M
    max_input_time: 300
    session_name: zbx_sessionid
    deny_gui_access: false
    warning_message: Zabbix Server is under maintenance
    access_ip_range: []
    # Advanced
    sso_settings: ""
    php_fpm_pm: dynamic
    php_fpm_pm_max_children: 50
    php_fpm_pm_start_servers: 5
    php_fpm_pm_min_spare_servers: 5
    php_fpm_pm_max_spare_servers: 35
    php_fpm_pm_max_requests: 0
  agent:
    enabled: true
    hostname:
      - Zabbix server
    hostname_item: ""
    metadata: ""
    metadata_item: ""
    timeout: 3
    enable_persistent_buffer: false
    persistent_buffer_period: 1h
    refresh_active_checks: 120
    buffer_send: 5
    buffer_size: 100
    unsafe_user_parameters: false
    tls_connect: unencrypted
    tls_accept:
      - unencrypted
    psk_identity: ""
    psk_file: ""
    allow_key: ""
    deny_key: ""
  javagateway:
    enabled: true
    start_pollers: 5
    timeout: 3
    debug_level: info
  webservice:
    enabled: true
    debug_level: 3
    timeout: 10
  snmptraps:
    enabled: true

envFrom:
  - secretRef:
      name: '{{ include "tc.common.names.fullname" . }}-common-secret'
  - configMapRef:
      name: '{{ include "tc.common.names.fullname" . }}-common-config'
  - configMapRef:
      name: '{{ include "tc.common.names.fullname" . }}-server-config'

service:
  main:
    ports:
      main:
        port: 10211
        protocol: http
        targetPort: 8080
  server:
    enabled: true
    ports:
      server:
        enabled: true
        protocol: tcp
        port: 10051
  javagateway:
    enabled: true
    ports:
      javagateway:
        enabled: true
        protocol: tcp
        port: 10052
  snmptraps:
    enabled: true
    ports:
      snmptraps:
        protocol: udp
        enabled: true
        port: 162
        targetPort: 1162
  agent:
    type: ClusterIP
    enabled: true
    ports:
      agent:
        enabled: true
        protocol: tcp
        port: 10050
  webservice:
    type: ClusterIP
    enabled: true
    ports:
      webservice:
        enabled: true
        protocol: http
        port: 10053

livenessprobe:
  enabled: true
  path: /-/healthy
  initialDelaySeconds: 0
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 120
  successThreshold: 1
  port: "{{ .Values.service.server.ports.server.port }}"
readinessprobe:
  enabled: true
  path: /-/ready
  initialDelaySeconds: 0
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 120
  successThreshold: 1
  port: "{{ .Values.service.server.ports.server.port }}"
startupprobe:
  enabled: true
  path: /-/ready
  initialDelaySeconds: 0
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 120
  successThreshold: 1
  port: "{{ .Values.service.server.ports.server.port }}"

persistence:
  # Server
  serverconf:
    enabled: true
    noMount: true
    mountPath: /etc/zabbix/
    size: 256Gi
  serveralertscripts:
    enabled: true
    mountPath: "/usr/lib/zabbix/alertscripts"
    size: 256Gi
  serverexternalscripts:
    enabled: true
    mountPath: "/usr/lib/zabbix/externalscripts"
    size: 256Gi
  servermodules:
    enabled: true
    mountPath: "/var/lib/zabbix/modules"
    size: 256Gi
  serverenc:
    enabled: true
    mountPath: "/var/lib/zabbix/enc"
    size: 256Gi
  serversshkeys:
    enabled: true
    mountPath: "/var/lib/zabbix/ssh_keys"
    size: 256Gi
  serversslcerts:
    enabled: true
    mountPath: "/var/lib/zabbix/ssl/certs"
    size: 256Gi
  serversslkeys:
    enabled: true
    mountPath: "/var/lib/zabbix/ssl/keys"
    size: 256Gi
  serversslca:
    enabled: true
    mountPath: "/var/lib/zabbix/ssl/ssl_ca"
    size: 256Gi
  serverexport:
    # Used with conjunction of .Values.zabbix.server.export_file_size
    enabled: true
    mountPath: "/var/lib/zabbix/export"
    size: 256Gi
  # SNMP Traps and Server
  snmptraps:
    enabled: true
    mountPath: /var/lib/zabbix/snmptraps
    size: 256Gi
  snmpmibs:
    enabled: true
    mountPath: /var/lib/zabbix/mibs
    size: 256Gi
  # Agent2 Volumes
  hostproc:
    enabled: true
    noMount: true
    readOnly: true
    type: hostPath
    hostPath: /proc
    mountPath: /host/proc
  hostsys:
    enabled: true
    noMount: true
    readOnly: true
    type: hostPath
    hostPath: /sys
    mountPath: /host/sys
  agentconf:
    enabled: true
    noMount: true
    mountPath: /etc/zabbix/zabbix_agentd.d
    size: 256Gi
#  agentenc:
#    enabled: true
#    noMount: true
#    mountPath: /var/lib/zabbix/enc
#    size: 256Gi
  agentbuffer:
    enabled: true
    noMount: true
    mountPath: /var/lib/zabbix/buffer
    size: 256Gi
  # Java Gateway
  javagatewaylibs:
    enabled: true
    noMount: true
    mountPath: /usr/sbin/zabbix_java/ext_lib
    size: 256Gi

cnpg:
  main:
    enabled: true
    user: zabbix
    database: zabbix

portal:
  open:
    enabled: true
